[package]
name = "random-bot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.41"

[package.metadata.component]
package = "chess:random-bot"

[package.metadata.component.target]
path = "../../wit"
world = "chess-bot"
